### ISSUE TITLE
doesn't recognize existing IPTC data until I read/save the data elsewhere

### ISSUE THREAD

**Issue by konnycode** [james-see/iptcinfo3#28]
Hi, 
I'm often working with images from a media agency. I noticed that iptcinfo3 fails to recognize IPTC data in their particular fotos. It must be the software they use to save them. When I open the picture with IrfanView and read the IPTC data there and save it again with "Write", it's also being picked up by iptcinfo3. So I'd have to open all pictures, read/write the existing data and then read them with iptcinfo3, which kind of defeats the purpose. Do you have any idea what that might be?
cheers

**Comment by jamesacampbell** [comment]
I believe this is the difference between the XMP set of image metadata in IPTC format and the IIM set of image metadata in IPTC format. Here is an example: ![](https://i.imgur.com/ykoBoZz.png) you can see that even though the fields may be similar, they are different sections. Some software (ADOBE mainly) write using XMP because they basically created that section as a subset of IPTC for their use in 2001. 

Try to upload an example image here: https://getpmd.iptc.org/getiptcpmd.html and see what the results are. You should see data in only the XMP fields, then after you open in IrfanView and save it with write, and upload again and check, you will see the IIM fields populated as well. 

Let me know how those tests go.

**Comment by james-see** [comment]
closing since stale. please re-open if new.
